#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HeartsScorecard.Resource", IsApplication=true)]

namespace HeartsScorecard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int babyblue = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int black = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int skyblue = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int displayScore1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int displayScore2 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int displayScore3 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int displayScore4 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int displayScore5 = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int nameRow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int player1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int player2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int player3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int player4 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int player5 = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int scoreA1 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int scoreA2 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int scoreA3 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int scoreA4 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int scoreA5 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int scoreB1 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int scoreB2 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int scoreB3 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int scoreB4 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int scoreB5 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int scoreC1 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int scoreC2 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int scoreC3 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int scoreC4 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int scoreC5 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int scoreD1 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int scoreD2 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int scoreD3 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int scoreD4 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int scoreD5 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int scoreE1 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int scoreE2 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int scoreE3 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int scoreE4 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int scoreE5 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int scoreF1 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int scoreF2 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int scoreF3 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int scoreF4 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int scoreF5 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int scoreG1 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int scoreG2 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int scoreG3 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int scoreG4 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int scoreG5 = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int scoreH1 = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int scoreH2 = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int scoreH3 = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int scoreH4 = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int scoreH5 = 2131165236;
			
			// aapt resource value: 0x7f070006
			public const int scoreRow = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int scoreRow1 = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int rowCount = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int App_Theme = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int FinalScoreStyle = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int NameStyle = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int RowStyle = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ScoreStyle = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
