#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HeartsScorecard.Resource", IsApplication=true)]

namespace HeartsScorecard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int playerCount3 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int playerCount4 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int playerCount5 = 2131165186;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f08000d
			public const int aqua = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int babyblue = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int black = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int blue = 2131230737;
			
			// aapt resource value: 0x7f080008
			public const int gray = 2131230728;
			
			// aapt resource value: 0x7f080010
			public const int green = 2131230736;
			
			// aapt resource value: 0x7f080007
			public const int lightgray = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public const int lime = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int maroon = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int navy = 2131230738;
			
			// aapt resource value: 0x7f080009
			public const int olive = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int orange = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int pink = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int purple = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int red = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int silver = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int skyblue = 2131230721;
			
			// aapt resource value: 0x7f08000f
			public const int teal = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int white = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int yellow = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_flip_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_notifications_active_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_play_arrow_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_refresh_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Jaws = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int progress_drawable_blue = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int progress_drawable_green = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int progress_drawable_orange = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int progress_drawable_purple = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int progress_drawable_red = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Wololo = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0079
			public const int ClearAllFields = 2131361913;
			
			// aapt resource value: 0x7f0a0077
			public const int JawsRingtone = 2131361911;
			
			// aapt resource value: 0x7f0a0012
			public const int PlayInstruction = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int ScoresSection = 2131361811;
			
			// aapt resource value: 0x7f0a0074
			public const int SetShareCardArrows = 2131361908;
			
			// aapt resource value: 0x7f0a0076
			public const int ShameBell = 2131361910;
			
			// aapt resource value: 0x7f0a0075
			public const int SwitchScoreView = 2131361909;
			
			// aapt resource value: 0x7f0a0078
			public const int WololoRingtone = 2131361912;
			
			// aapt resource value: 0x7f0a0007
			public const int displayScore1 = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int displayScore2 = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int displayScore3 = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int displayScore4 = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int displayScore5 = 2131361803;
			
			// aapt resource value: 0x7f0a0000
			public const int nameRow = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int player1 = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int player2 = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int player3 = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int player4 = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int player5 = 2131361797;
			
			// aapt resource value: 0x7f0a0014
			public const int round01 = 2131361812;
			
			// aapt resource value: 0x7f0a001a
			public const int round02 = 2131361818;
			
			// aapt resource value: 0x7f0a0020
			public const int round03 = 2131361824;
			
			// aapt resource value: 0x7f0a0026
			public const int round04 = 2131361830;
			
			// aapt resource value: 0x7f0a002c
			public const int round05 = 2131361836;
			
			// aapt resource value: 0x7f0a0032
			public const int round06 = 2131361842;
			
			// aapt resource value: 0x7f0a0038
			public const int round07 = 2131361848;
			
			// aapt resource value: 0x7f0a003e
			public const int round08 = 2131361854;
			
			// aapt resource value: 0x7f0a0044
			public const int round09 = 2131361860;
			
			// aapt resource value: 0x7f0a004a
			public const int round10 = 2131361866;
			
			// aapt resource value: 0x7f0a0050
			public const int round11 = 2131361872;
			
			// aapt resource value: 0x7f0a0056
			public const int round12 = 2131361878;
			
			// aapt resource value: 0x7f0a005c
			public const int round13 = 2131361884;
			
			// aapt resource value: 0x7f0a0062
			public const int round14 = 2131361890;
			
			// aapt resource value: 0x7f0a0068
			public const int round15 = 2131361896;
			
			// aapt resource value: 0x7f0a006e
			public const int round16 = 2131361902;
			
			// aapt resource value: 0x7f0a0015
			public const int scoreA1 = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int scoreA2 = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int scoreA3 = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int scoreA4 = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int scoreA5 = 2131361817;
			
			// aapt resource value: 0x7f0a001b
			public const int scoreB1 = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int scoreB2 = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int scoreB3 = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int scoreB4 = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int scoreB5 = 2131361823;
			
			// aapt resource value: 0x7f0a0021
			public const int scoreC1 = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int scoreC2 = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int scoreC3 = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int scoreC4 = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int scoreC5 = 2131361829;
			
			// aapt resource value: 0x7f0a0027
			public const int scoreD1 = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int scoreD2 = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int scoreD3 = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int scoreD4 = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int scoreD5 = 2131361835;
			
			// aapt resource value: 0x7f0a002d
			public const int scoreE1 = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int scoreE2 = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int scoreE3 = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int scoreE4 = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int scoreE5 = 2131361841;
			
			// aapt resource value: 0x7f0a0033
			public const int scoreF1 = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int scoreF2 = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int scoreF3 = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int scoreF4 = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int scoreF5 = 2131361847;
			
			// aapt resource value: 0x7f0a0039
			public const int scoreG1 = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int scoreG2 = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int scoreG3 = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int scoreG4 = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int scoreG5 = 2131361853;
			
			// aapt resource value: 0x7f0a003f
			public const int scoreH1 = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int scoreH2 = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int scoreH3 = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int scoreH4 = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int scoreH5 = 2131361859;
			
			// aapt resource value: 0x7f0a0045
			public const int scoreI1 = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public const int scoreI2 = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int scoreI3 = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int scoreI4 = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int scoreI5 = 2131361865;
			
			// aapt resource value: 0x7f0a004b
			public const int scoreJ1 = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int scoreJ2 = 2131361868;
			
			// aapt resource value: 0x7f0a004d
			public const int scoreJ3 = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int scoreJ4 = 2131361870;
			
			// aapt resource value: 0x7f0a004f
			public const int scoreJ5 = 2131361871;
			
			// aapt resource value: 0x7f0a0051
			public const int scoreK1 = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int scoreK2 = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int scoreK3 = 2131361875;
			
			// aapt resource value: 0x7f0a0054
			public const int scoreK4 = 2131361876;
			
			// aapt resource value: 0x7f0a0055
			public const int scoreK5 = 2131361877;
			
			// aapt resource value: 0x7f0a0057
			public const int scoreL1 = 2131361879;
			
			// aapt resource value: 0x7f0a0058
			public const int scoreL2 = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int scoreL3 = 2131361881;
			
			// aapt resource value: 0x7f0a005a
			public const int scoreL4 = 2131361882;
			
			// aapt resource value: 0x7f0a005b
			public const int scoreL5 = 2131361883;
			
			// aapt resource value: 0x7f0a005d
			public const int scoreM1 = 2131361885;
			
			// aapt resource value: 0x7f0a005e
			public const int scoreM2 = 2131361886;
			
			// aapt resource value: 0x7f0a005f
			public const int scoreM3 = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int scoreM4 = 2131361888;
			
			// aapt resource value: 0x7f0a0061
			public const int scoreM5 = 2131361889;
			
			// aapt resource value: 0x7f0a0063
			public const int scoreN1 = 2131361891;
			
			// aapt resource value: 0x7f0a0064
			public const int scoreN2 = 2131361892;
			
			// aapt resource value: 0x7f0a0065
			public const int scoreN3 = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int scoreN4 = 2131361894;
			
			// aapt resource value: 0x7f0a0067
			public const int scoreN5 = 2131361895;
			
			// aapt resource value: 0x7f0a0069
			public const int scoreO1 = 2131361897;
			
			// aapt resource value: 0x7f0a006a
			public const int scoreO2 = 2131361898;
			
			// aapt resource value: 0x7f0a006b
			public const int scoreO3 = 2131361899;
			
			// aapt resource value: 0x7f0a006c
			public const int scoreO4 = 2131361900;
			
			// aapt resource value: 0x7f0a006d
			public const int scoreO5 = 2131361901;
			
			// aapt resource value: 0x7f0a006f
			public const int scoreP1 = 2131361903;
			
			// aapt resource value: 0x7f0a0070
			public const int scoreP2 = 2131361904;
			
			// aapt resource value: 0x7f0a0071
			public const int scoreP3 = 2131361905;
			
			// aapt resource value: 0x7f0a0072
			public const int scoreP4 = 2131361906;
			
			// aapt resource value: 0x7f0a0073
			public const int scoreP5 = 2131361907;
			
			// aapt resource value: 0x7f0a000d
			public const int scoreProgress1 = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int scoreProgress2 = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int scoreProgress3 = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int scoreProgress4 = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int scoreProgress5 = 2131361809;
			
			// aapt resource value: 0x7f0a000c
			public const int scoreProgressBarRow = 2131361804;
			
			// aapt resource value: 0x7f0a0006
			public const int scoreTextViewRow = 2131361798;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int rowCount = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Jaws = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Shame = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Wololo = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int AppTextLabel = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int App_Theme = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int CellStyle = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int FinalScoreStyle = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int NameStyle = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ProgressBarStyle = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int RowStyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int RowStyleForFinalScore = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int ScoreStyle = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ShareCardStyle = 2131034121;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
